"""
This package contains tests to be run with "nosetests".

On Windows, tests are run automatically for every commit, thanks to AppVeyor.
    See: appveyor.yml

On Linux, tests are run automatically for every commit, thanks to Travis CI.
    See: .travis.yml

On Mac OS X, tests can be run manually with:
    python setup.py nosetests
Coverage can be reported with:
    coverage report -m
and coverage can be uploaded with:
    codecov -X gcov

"python setup.py nosetests" generates a .coverage file, which is necessary to
run "coverage report -m".  It should be removed before subsequent runs of
"python setup.py nosetests" to ensure that recently deleted lines of code
are not included.

Similarly, coverage.xml (generated by "codecov") should be removed before
subsequent "codecov" runs to ensure an accurate coverage report.
"""
import os
import sys
import tempfile
import unittest

import wx

from ..events import MYDATA_EVENTS
from ..settings import SETTINGS
from ..models.settings import SettingsModel
from ..models.settings.validation import ValidateSettings
from ..dataviewmodels.folders import FoldersModel
from ..dataviewmodels.users import UsersModel
from ..dataviewmodels.groups import GroupsModel
from .utils import StartFakeMyTardisServer
from .utils import WaitForFakeMyTardisServerToStart
if sys.platform.startswith("linux"):
    from ..linuxsubprocesses import StopErrandBoy


class MyDataMinimalTester(unittest.TestCase):
    """
    Lightweight class to derive from for tests requiring the
    MYDATA_TESTING environment variable to be set.
    """
    def setUp(self):
        os.environ['MYDATA_TESTING'] = 'True'

    def tearDown(self):
        del os.environ['MYDATA_TESTING']


class MyDataTester(unittest.TestCase):
    """
    Base class for inheriting from for tests requiring a fake MyTardis server
    """
    def __init__(self, *args, **kwargs):
        super(MyDataTester, self).__init__(*args, **kwargs)
        self.app = None
        self.frame = None
        self.httpd = None
        self.fakeMyTardisHost = "127.0.0.1"
        self.fakeMyTardisPort = None
        self.fakeMyTardisServerThread = None
        self.fakeMyTardisUrl = None
        self.usersModel = None
        self.groupsModel = None
        self.foldersModel = None

    def setUp(self):
        os.environ['MYDATA_TESTING'] = 'True'
        MYDATA_EVENTS.InitializeWithNotifyWindow(self.frame)
        self.fakeMyTardisHost, self.fakeMyTardisPort, self.httpd, \
            self.fakeMyTardisServerThread = StartFakeMyTardisServer()
        self.fakeMyTardisUrl = \
            "http://%s:%s" % (self.fakeMyTardisHost, self.fakeMyTardisPort)
        WaitForFakeMyTardisServerToStart(self.fakeMyTardisUrl)

    def InitializeAppAndFrame(self, title):
        """
        Initialize generic wxPython app and main frame
        """
        self.app = wx.App()
        self.app.okToShowModalDialogs = False
        self.frame = wx.Frame(parent=None, title=title)

    def tearDown(self):
        del os.environ['MYDATA_TESTING']
        if self.frame:
            self.frame.Hide()
            self.frame.Destroy()
        if self.httpd:
            self.httpd.shutdown()
        if self.fakeMyTardisServerThread:
            self.fakeMyTardisServerThread.join()
        if sys.platform.startswith("linux"):
            StopErrandBoy()

    def UpdateSettingsFromCfg(self, configName, dataFolderName=None):
        """
        Update the global settings instance from a test MyData.cfg file and
        update the dataDirectory and myTardisUrl for the test environment.
        """
        pathToTestConfig = os.path.join(
            os.path.dirname(os.path.realpath(__file__)),
            "testdata/%s.cfg" % configName)
        try:
            self.assertTrue(os.path.exists(pathToTestConfig))
        except AssertionError:
            sys.stderr.write("Config path: %s\n" % pathToTestConfig)
            raise
        SETTINGS.Update(SettingsModel(pathToTestConfig))
        if not dataFolderName:
            dataFolderName = configName
        dataDirectory = os.path.join(
            os.path.dirname(os.path.realpath(__file__)),
            "testdata", dataFolderName)
        try:
            self.assertTrue(os.path.exists(dataDirectory))
        except AssertionError:
            sys.stderr.write("Data directory: %s\n" % dataDirectory)
            raise
        SETTINGS.general.dataDirectory = dataDirectory
        SETTINGS.general.myTardisUrl = self.fakeMyTardisUrl
        SETTINGS.miscellaneous.cacheDataFileLookups = False

    def InitializeModels(self):
        """
        Initialize dataview models.

        Should be called after loading valid settings.
        """
        self.usersModel = UsersModel()
        self.groupsModel = GroupsModel()
        self.foldersModel = FoldersModel(self.usersModel, self.groupsModel)

    def AssertUsers(self, users):
        """
        Check the users in self.usersModel
        """
        self.assertEqual(
            sorted(self.usersModel.GetValuesForColname("Username")), users)

    def AssertFolders(self, folders):
        """
        Check the folders in self.foldersModel
        """
        folderNames = []
        for row in range(self.foldersModel.GetRowCount()):
            folderNames.append(
                self.foldersModel.GetFolderRecord(row).folderName)
        self.assertEqual(sorted(folderNames), folders)

    def AssertNumFiles(self, numFiles):
        """
        Check the number of files found in self.foldersModel
        """
        totalFiles = 0
        for row in range(self.foldersModel.GetRowCount()):
            totalFiles += self.foldersModel.GetFolderRecord(row).GetNumFiles()
        self.assertEqual(totalFiles, numFiles)


class MyDataSettingsTester(MyDataTester):
    """
    Base class for inheriting from for tests requiring a fake MyTardis server
    """
    def __init__(self, *args, **kwargs):
        super(MyDataSettingsTester, self).__init__(*args, **kwargs)
        # Used for saving MyData.cfg:
        self.tempFilePath = None

    def setUp(self):
        super(MyDataSettingsTester, self).setUp()
        with tempfile.NamedTemporaryFile() as tempConfig:
            self.tempFilePath = tempConfig.name

    def tearDown(self):
        super(MyDataSettingsTester, self).tearDown()
        if os.path.exists(self.tempFilePath):
            os.remove(self.tempFilePath)

    def UpdateSettingsFromCfg(self, configName, dataFolderName=None):
        """
        Update the global settings instance from a test MyData.cfg file and
        update the dataDirectory and myTardisUrl for the test environment.
        """
        super(MyDataSettingsTester, self).UpdateSettingsFromCfg(
            configName, dataFolderName)
        SETTINGS.configPath = self.tempFilePath


class MyDataScanFoldersTester(MyDataTester):
    """
    Base class for inheriting from for tests requiring a fake MyTardis server

    Includes callbacks used by ScanFolders.
    """
    @staticmethod
    def ProgressCallback(numUserOrGroupFoldersScanned):
        """
        Callback for ScanFolders.
        """
        assert numUserOrGroupFoldersScanned > 0

    @staticmethod
    def ShouldAbort():
        """
        Callback for ScanFolders.
        """
        return False

    def ScanFolders(self):
        """
        Collecting some common code needed by multiple "scan folders" tests
        """
        ValidateSettings()
        self.InitializeModels()
        self.foldersModel.ScanFolders(
            MyDataScanFoldersTester.ProgressCallback,
            MyDataScanFoldersTester.ShouldAbort)
